
// Generated by dojo-bindgen on Sat, 7 Sep 2024 19:09:24 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript` 
import { Account, byteArray } from "starknet";
import { DojoProvider } from "@dojoengine/core";
import * as models from "./models.gen";

export type IWorld = Awaited<ReturnType<typeof setupWorld>>;

export async function setupWorld(provider: DojoProvider) {
    // System definitions for `rl_chess-lobby` contract
    function lobby() {
        const contract_name = "lobby";

        
        // Call the `register_player` system with the specified Account and calldata
        const register_player = async (props: { account: Account, name: bigint, profile_pic_type: models.ProfilePicType, profile_pic_uri: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "register_player",
                        calldata: [props.name,
                ["Undefined", "Native", "External"].indexOf(props.profile_pic_type.type),
                props.profile_pic_uri],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `update_player` system with the specified Account and calldata
        const update_player = async (props: { account: Account, name: bigint, profile_pic_type: models.ProfilePicType, profile_pic_uri: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "update_player",
                        calldata: [props.name,
                ["Undefined", "Native", "External"].indexOf(props.profile_pic_type.type),
                props.profile_pic_uri],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `invite` system with the specified Account and calldata
        const invite = async (props: { account: Account, game_format_id: number, invitee_address: bigint, invite_expiry: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "invite",
                        calldata: [props.game_format_id,
                props.invitee_address,
                props.invite_expiry],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `reply_invite` system with the specified Account and calldata
        const reply_invite = async (props: { account: Account, game_id: bigint, accepted: boolean }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "reply_invite",
                        calldata: [props.game_id,
                props.accepted],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `create_game` system with the specified Account and calldata
        const create_game = async (props: { account: Account, game_format_id: number }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "create_game",
                        calldata: [props.game_format_id],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `join_game` system with the specified Account and calldata
        const join_game = async (props: { account: Account, game_id: bigint }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "join_game",
                        calldata: [props.game_id],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

    
        // Call the `world` system with the specified Account and calldata
        const world = async (props: { account: Account }) => {
            try {
                return await provider.execute(
                    props.account,
                    {
                        contractName: contract_name,
                        entrypoint: "world",
                        calldata: [],
                    },
                    "rl_chess"
                );
            } catch (error) {
                console.error("Error executing spawn:", error);
                throw error;
            }
        };
            

        return {
            register_player, update_player, invite, reply_invite, create_game, join_game, world
        };
    }

    return {
        lobby: lobby()
    };
}
