kind = "DojoModel"
class_hash = "0x7722d5c63e5efd7f580ac50ac3563c0affec6748504d8b46e4cb4f302945af6"
original_class_hash = "0x7722d5c63e5efd7f580ac50ac3563c0affec6748504d8b46e4cb4f302945af6"
abi = "manifests/dev/base/abis/models/rl_chess-Board-2cc709f8.json"
tag = "rl_chess-Board"
manifest_name = "rl_chess-Board-2cc709f8"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "pieces"
type = "Array<u64>"
key = false

[[members]]
name = "colors"
type = "Array<u64>"
key = false

[[members]]
name = "side_to_move"
type = "Color"
key = false

[[members]]
name = "castling_rights"
type = "u8"
key = false

[[members]]
name = "en_passant"
type = "u8"
key = false

[[members]]
name = "halfmove_clock"
type = "u8"
key = false

[[members]]
name = "fullmove_number"
type = "u16"
key = false

[[members]]
name = "move_history"
type = "Array<(u8, u8)>"
key = false

[[members]]
name = "move_history_string"
type = "Array<felt252>"
key = false

[[members]]
name = "last_move_time"
type = "u64"
key = false
