kind = "DojoModel"
class_hash = "0x5ec028775b8802b5c6bd8c744a98a84a5666f4b7fb885416cf5c96bac2be527"
original_class_hash = "0x5ec028775b8802b5c6bd8c744a98a84a5666f4b7fb885416cf5c96bac2be527"
abi = "manifests/dev/base/abis/models/rl_chess-Board-2cc709f8.json"
tag = "rl_chess-Board"
manifest_name = "rl_chess-Board-2cc709f8"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "whites"
type = "u64"
key = false

[[members]]
name = "blacks"
type = "u64"
key = false

[[members]]
name = "pawns"
type = "u64"
key = false

[[members]]
name = "rooks"
type = "u64"
key = false

[[members]]
name = "knights"
type = "u64"
key = false

[[members]]
name = "bishops"
type = "u64"
key = false

[[members]]
name = "queens"
type = "u64"
key = false

[[members]]
name = "kings"
type = "u64"
key = false

[[members]]
name = "side_to_move"
type = "Color"
key = false

[[members]]
name = "castling_rights"
type = "u8"
key = false

[[members]]
name = "en_passant"
type = "u8"
key = false

[[members]]
name = "halfmove_clock"
type = "u8"
key = false

[[members]]
name = "fullmove_number"
type = "u16"
key = false

[[members]]
name = "last_move_time"
type = "u64"
key = false
