kind = "DojoModel"
class_hash = "0x5f98989ea987972fa15146b6ab078e63ea3783d1ca97e2edc930ff826933910"
original_class_hash = "0x5f98989ea987972fa15146b6ab078e63ea3783d1ca97e2edc930ff826933910"
abi = "manifests/dev/base/abis/models/rl_chess-Player-737dac4e.json"
tag = "rl_chess-Player"
manifest_name = "rl_chess-Player-737dac4e"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "profile_pic_type"
type = "ProfilePicType"
key = false

[[members]]
name = "profile_pic_uri"
type = "u64"
key = false

[[members]]
name = "timestamp"
type = "u64"
key = false
