kind = "DojoModel"
class_hash = "0x453bb6786bc7586bc2194dc2daea858fa6ffb655e2fb63b60ef16246faa1ec"
original_class_hash = "0x453bb6786bc7586bc2194dc2daea858fa6ffb655e2fb63b60ef16246faa1ec"
abi = "manifests/slot/base/abis/models/rl_chess-Format-6da30a59.json"
tag = "rl_chess-Format"
manifest_name = "rl_chess-Format-6da30a59"

[[members]]
name = "format_id"
type = "u16"
key = true

[[members]]
name = "description"
type = "felt252"
key = false

[[members]]
name = "turn_expiry"
type = "u64"
key = false

[[members]]
name = "total_time_per_side"
type = "u64"
key = false

[[members]]
name = "total_time_string"
type = "felt252"
key = false

[[members]]
name = "increment"
type = "u8"
key = false

[[members]]
name = "available"
type = "bool"
key = false
