kind = "DojoContract"
class_hash = "0x27f3eeba60ef02ab70761eed6993c640cc5d120e6ddf6250ba57ef38a6f17e9"
original_class_hash = "0x27f3eeba60ef02ab70761eed6993c640cc5d120e6ddf6250ba57ef38a6f17e9"
base_class_hash = "0x0"
abi = "manifests/slot/base/abis/contracts/rl_chess-room-2dc7c374.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess-room"
systems = ["move"]
manifest_name = "rl_chess-room-2dc7c374"
