kind = "DojoContract"
class_hash = "0x54fb9ec0a586d7468554472eb5a9611b0bbaf7cd237ba08fe56554e4327a4f4"
original_class_hash = "0x54fb9ec0a586d7468554472eb5a9611b0bbaf7cd237ba08fe56554e4327a4f4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess-lobby-aac486b8.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess-lobby"
systems = [
    "register_player",
    "update_player",
]
manifest_name = "rl_chess-lobby-aac486b8"
