kind = "DojoContract"
class_hash = "0x336819daae9fd253a5c30a2403904a15d8fd550b94ba4d0af65c3131f69e02a"
original_class_hash = "0x336819daae9fd253a5c30a2403904a15d8fd550b94ba4d0af65c3131f69e02a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess-lobby-aac486b8.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess-lobby"
systems = [
    "update_player",
    "update_invitee",
    "reply_invite",
    "create_game",
    "join_game",
    "leave_game",
    "owner_withdraw_game",
    "ready_up",
    "start_game",
    "switch_sides",
]
manifest_name = "rl_chess-lobby-aac486b8"
