kind = "DojoContract"
class_hash = "0x5d7cb94d76eb9703c703ca516d8fc154840f42baac171871d08141cea92ea8e"
original_class_hash = "0x5d7cb94d76eb9703c703ca516d8fc154840f42baac171871d08141cea92ea8e"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess-lobby-aac486b8.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess-lobby"
systems = [
    "update_player",
    "update_invitee",
    "reply_invite",
    "join_game",
    "leave_game",
    "owner_withdraw_game",
    "ready_up",
    "start_game",
    "switch_sides",
]
manifest_name = "rl_chess-lobby-aac486b8"
