kind = "DojoContract"
class_hash = "0x708c1846eefe0449a71a0f616892e5ff839115e0bf123e05b5ad9300b69d18f"
original_class_hash = "0x708c1846eefe0449a71a0f616892e5ff839115e0bf123e05b5ad9300b69d18f"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess-lobby-aac486b8.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess-lobby"
systems = [
    "update_player",
    "update_invitee",
    "reply_invite",
    "join_game",
    "leave_game",
    "owner_withdraw_game",
    "ready_up",
    "start_game",
    "switch_sides",
]
manifest_name = "rl_chess-lobby-aac486b8"
