kind = "DojoContract"
class_hash = "0x54e4b01e4cb4d2d2eb3f7385eeae7d2bbf6f209b420f5c5eeb9d2cce5f973bd"
original_class_hash = "0x54e4b01e4cb4d2d2eb3f7385eeae7d2bbf6f209b420f5c5eeb9d2cce5f973bd"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/rl_chess-lobby-aac486b8.json"
reads = []
writes = []
init_calldata = []
tag = "rl_chess-lobby"
systems = [
    "update_player",
    "update_invitee",
    "reply_invite",
    "join_game",
    "leave_game",
    "owner_withdraw_game",
    "ready_up",
    "start_game",
    "switch_sides",
]
manifest_name = "rl_chess-lobby-aac486b8"
